### ISSUE TITLE
Modify Checklist

### ISSUE THREAD

**Issue by sgoodwin** [shrdev/Checklists#3]
- [ ] "checklistText" can just be "text"
- [ ] "text" should be a constant, users can't modify the text
- [ ] Checklist can be a struct, there's no need for it to be a class.
